/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DiaDosPaisRouteImport } from './routes/dia-dos-pais'
import { Route as MiniSaladaRouteImport } from './routes/mini-salada'
import { Route as MonteRouteImport } from './routes/monte'
import { Route as ProntosRouteImport } from './routes/prontos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaDosPaisRoute = DiaDosPaisRouteImport.update({
  id: '/dia-dos-pais',
  path: '/dia-dos-pais',
  getParentRoute: () => rootRouteImport,
} as any)
const MiniSaladaRoute = MiniSaladaRouteImport.update({
  id: '/mini-salada',
  path: '/mini-salada',
  getParentRoute: () => rootRouteImport,
} as any)
const MonteRoute = MonteRouteImport.update({
  id: '/monte',
  path: '/monte',
  getParentRoute: () => rootRouteImport,
} as any)
const ProntosRoute = ProntosRouteImport.update({
  id: '/prontos',
  path: '/prontos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/dia-dos-pais': typeof DiaDosPaisRoute
  '/mini-salada': typeof MiniSaladaRoute
  '/monte': typeof MonteRoute
  '/prontos': typeof ProntosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/dia-dos-pais': typeof DiaDosPaisRoute
  '/mini-salada': typeof MiniSaladaRoute
  '/monte': typeof MonteRoute
  '/prontos': typeof ProntosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/dia-dos-pais': typeof DiaDosPaisRoute
  '/mini-salada': typeof MiniSaladaRoute
  '/monte': typeof MonteRoute
  '/prontos': typeof ProntosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/checkout' | '/dia-dos-pais' | '/mini-salada' | '/monte' | '/prontos'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/checkout' | '/dia-dos-pais' | '/mini-salada' | '/monte' | '/prontos'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/dia-dos-pais'
    | '/mini-salada'
    | '/monte'
    | '/prontos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  DiaDosPaisRoute: typeof DiaDosPaisRoute
  MiniSaladaRoute: typeof MiniSaladaRoute
  MonteRoute: typeof MonteRoute
  ProntosRoute: typeof ProntosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dia-dos-pais': {
      id: '/dia-dos-pais'
      path: '/dia-dos-pais'
      fullPath: '/dia-dos-pais'
      preLoaderRoute: typeof DiaDosPaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mini-salada': {
      id: '/mini-salada'
      path: '/mini-salada'
      fullPath: '/mini-salada'
      preLoaderRoute: typeof MiniSaladaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monte': {
      id: '/monte'
      path: '/monte'
      fullPath: '/monte'
      preLoaderRoute: typeof MonteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prontos': {
      id: '/prontos'
      path: '/prontos'
      fullPath: '/prontos'
      preLoaderRoute: typeof ProntosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  DiaDosPaisRoute: DiaDosPaisRoute,
  MiniSaladaRoute: MiniSaladaRoute,
  MonteRoute: MonteRoute,
  ProntosRoute: ProntosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
