/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as MonteRouteImport } from './routes/monte'
import { Route as ProntosRouteImport } from './routes/prontos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const MonteRoute = MonteRouteImport.update({
  id: '/monte',
  path: '/monte',
  getParentRoute: () => rootRouteImport,
} as any)
const ProntosRoute = ProntosRouteImport.update({
  id: '/prontos',
  path: '/prontos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/monte': typeof MonteRoute
  '/prontos': typeof ProntosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/monte': typeof MonteRoute
  '/prontos': typeof ProntosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/monte': typeof MonteRoute
  '/prontos': typeof ProntosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/checkout' | '/monte' | '/prontos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/checkout' | '/monte' | '/prontos'
  id: '__root__' | '/' | '/checkout' | '/monte' | '/prontos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  MonteRoute: typeof MonteRoute
  ProntosRoute: typeof ProntosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monte': {
      id: '/monte'
      path: '/monte'
      fullPath: '/monte'
      preLoaderRoute: typeof MonteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prontos': {
      id: '/prontos'
      path: '/prontos'
      fullPath: '/prontos'
      preLoaderRoute: typeof ProntosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  MonteRoute: MonteRoute,
  ProntosRoute: ProntosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
